api_platform:
    title: 'MONGAZ API'
    version: '1.0.0'
    defaults:
        pagination_items_per_page: 20
        normalization_context: { groups: ['read'] }
        denormalization_context: { groups: ['write'] }
        security: "is_granted('ROLE_USER')" # optional, default security
    formats:
        jsonld:  ['application/ld+json']
        json:    ['application/json']       
        
    # Expose JWT as a security scheme
    swagger:
        versions: [3]
        api_keys:
            bearer:
                name: Authorization
                type: http
                scheme: bearer
                bearerFormat: JWT
    swagger_ui_extra_configuration:
        persistAuthorization: true  # keeps token in Swagger UI
    openapi:
        swagger_ui_extra_configuration:
            persistAuthorization: true