framework:
    rate_limiter:
        login:
            policy: 'fixed_window'
            limit: 5
            interval: '1 minute'
        accept_order:
            policy: 'token_bucket'
            limit: 10
            rate: { interval: '1 minute', amount: 10 }
