security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  role_hierarchy:
    ROLE_SUPER_ADMIN: [ROLE_ADMIN]
    ROLE_ADMIN: [ROLE_USER]
    ROLE_DRIVER: [ROLE_USER]

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: phone   # <-- Use phone instead of username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern: ^/auth/login
      stateless: true
      json_login:
        check_path: /auth/login
        username_path: phone      # <-- Expect JSON { "phone": "...", "password": "..." }
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    refresh:
      pattern: ^/auth/refresh
      stateless: true

    api:
      pattern: ^/
      stateless: true
      jwt: ~

  access_control:
    - { path: ^/auth/login, roles: PUBLIC_ACCESS }
    - { path: ^/auth/refresh, roles: PUBLIC_ACCESS }
    - { path: ^/docs, roles: PUBLIC_ACCESS }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
