security:
    password_hashers:
        # Uses auto algorithm (bcrypt or sodium depending on PHP version)
        App\Entity\User:
            algorithm: auto

    providers:
        # Load user by phone (custom user provider still delegates to Doctrine)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: phone

    firewalls:
        # Disable security for dev/profiler
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Public endpoints (login, token refresh, docs)
        login:
            pattern:  ^/api/login
            stateless: true
            json_login:
                check_path:               /api/login
                username_path:            phone     # use phone instead of username/email
                password_path:            password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        refresh:
            pattern:  ^/api/token/refresh
            stateless: true
            security: false

        api:
            pattern:   ^/api
            stateless: true
            provider:  app_user_provider
            jwt:       ~

        main:
            lazy: true
            provider: app_user_provider
            logout: true

    access_control:
        # Allow anonymous access to login + refresh
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }

        # Allow API docs without auth
        - { path: ^/docs, roles: PUBLIC_ACCESS }

        # Admin restricted endpoints
        - { path: ^/api/admin, roles: ROLE_ADMIN }

        # Driver restricted endpoints
        - { path: ^/api/driver, roles: ROLE_DRIVER }

        # Default API endpoints require at least USER
        - { path: ^/api, roles: ROLE_USER }
