_security_logout:
    resource: security.route_loader.logout
    type: service
login:
    path: /api/login
    methods: [POST]

gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
    methods: [POST]
