controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
gesdinet_jwt_refresh_token:
    path: /auth/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
    methods: [POST]
